title: A new Blog on Data Vizualization with Python
description: This blog has been created to help you in becoming the new data viz ninja! Hosted by @andreagiussani

#theme: jekyll-theme-hacker
theme: jekyll-theme-cayman
github:
  is_project_page: false

plugins:
  - jekyll-feed

